---
title: "Analyses for 'The development of canonical proportion continues past toddlerhood'"
author: "Kasia Hitczenko"
date: '2023-04-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, load-packages, echo=FALSE}
# Load packages

library(plyr)
library(dplyr)
library(lme4)
library(influence.ME)
library(car)
library(ggplot2)
library(ggpubr)
library("RColorBrewer")
library("plotrix")
```

```{r, read-in-data}
# Read in combined data (created by commented-out code above)
df <- read.csv("../data/combined-data-for-analysis.csv", stringsAsFactors = FALSE)

# Set missing weights to the minimum weights value
df$n_speechlike[is.na(df$n_speechlike)] <- min(df$n_speechlike, na.rm = TRUE)

# Get syllabic complexity
langinfo <- read.csv("../data/LAAC_Internship2020_Languages.xlsx - Usable as csv.csv")
df$syllcomplexity[df$corpus == 'Yélî Dnye (N=41)'] <- langinfo$Maddieson_sylcomp[langinfo$Language == 'Yélî']
df$syllcomplexity[df$corpus == 'Quechua (N=3)'] <- langinfo$Maddieson_sylcomp[langinfo$Language == 'Quechua']
df$syllcomplexity[df$corpus == 'English-Bergelson (N=10)' | df$corpus == 'English-Seidl (N=10)'] <- langinfo$Maddieson_sylcomp[langinfo$Language == 'English']
df$syllcomplexity[df$corpus == 'Tseltal (N=10)'] <- langinfo$Maddieson_sylcomp[langinfo$Language == 'Tseltal']
df$syllcomplexity[df$corpus == 'French (N=10)'] <- langinfo$Maddieson_sylcomp[langinfo$Language == 'French']
df$syllcomplexity[df$corpus == 'Tsimane\' (N=30)'] <- langinfo$Maddieson_sylcomp[langinfo$Language == 'Tsimane']
df$syllcomplexity[df$corpus == 'Solomon (N=15)'] <- langinfo$Maddieson_sylcomp[langinfo$Language == 'Roviana']
df$syllcomplexity <- factor(df$syllcomplexity, levels = c("Low", "Moderate", "High"))

# Get rural vs. urban
df$urbrur[df$corpus == 'Yélî Dnye (N=41)'] <- 'Rural'
df$urbrur[df$corpus == 'Quechua (N=3)'] <- 'Rural'
df$urbrur[df$corpus == 'English-Bergelson (N=10)' | df$corpus == 'English-Seidl (N=10)'] <- 'Urban'
df$urbrur[df$corpus == 'Tseltal (N=10)'] <- 'Rural'
df$urbrur[df$corpus == 'French (N=10)'] <- 'Urban'
df$urbrur[df$corpus == 'Tsimane\' (N=30)'] <- 'Rural'
df$urbrur[df$corpus == 'Solomon (N=15)'] <- 'Rural'

```

## Regressions looking at the relationship between age and canonical proportion

```{r age-vs-cp, echo=FALSE}

# Calculate z-scored age + z-scored age^2 for regression
df$age_mo_round_z <- (df$age_mo_round - mean(df$age_mo_round))/sd(df$age_mo_round)
df$age_mo_round_sq <- df$age_mo_round_z**2
df$age_mo_round_sq_z <- (df$age_mo_round_sq - mean(df$age_mo_round_sq))/sd(df$age_mo_round_sq)

## fit initial model using all data
## running the full models (with slopes + intercepts) results in singular fit
## so we step back to just slopes; we compare a linear model to a quadratic model
# slopes & intercepts: age.model <- glmer(cp ~ age_mo_round_z + child_gender + (1+age_mo_round_z|corpus), data = df, family = binomial(), weights = n_speechlike)
age.model <- glmer(cp ~ age_mo_round_z + child_gender + (0+age_mo_round_z|corpus), data = df, family = binomial(), weights = n_speechlike)
# slopes & intercepts: agesqz.model <- glmer(cp ~ age_mo_round_sq_z + age_mo_round_z + child_gender + (1 + age_mo_round_z + age_mo_round_sq_z|corpus), data = df, family = binomial(), weights = n_speechlike)
agesqz.model <- glmer(cp ~ age_mo_round_sq_z + age_mo_round_z + child_gender + (0 + age_mo_round_z + age_mo_round_sq_z|corpus), data = df, family = binomial(), weights = n_speechlike)

summary(age.model)
summary(agesqz.model)
anova(age.model, agesqz.model)

```

## Regression 

## BUCLD 

This work was first presented at BUCLD 2022. The slides are available here: <https://khitczenko.github.io/BUCLD2022.pdf> and the following code creates the
plots included there.

```{r bucld-plots}

# 1. Canonical proportion by age, colored by corpus
p_corpus <- ggplot(df, aes(x = age_mo_round, y = cp, color = corpus)) + geom_point() + 
  xlab("Age (months)") + ylab("Canonical proportion") + 
  theme(legend.position="bottom") +
  guides(colour = guide_legend(nrow = 4)) + 
  theme(legend.title=element_blank()) + 
  geom_point(size=3)
p_corpus

# 2. Separate out each corpus and plot linear vs. quadratic lines
p_sep_by_corpus <- ggplot(df, aes(x = age_mo_round, y = cp)) +
  geom_point() +
  stat_smooth(method = "lm", formula = y ~ x + I(x^2), linewidth = 0.5, se = FALSE) +
  stat_smooth(method = 'lm', formula = y ~ x, linewidth = 0.5, se = FALSE, linetype = 'dashed') +
  facet_wrap(~ corpus, ncol = 2) +
  xlab("Age (months)") + ylab("Canonical Proportion") + 
  scale_color_manual(name='Regression Model', breaks=c('Linear', 'Quadratic'), values=c('Quadratic'='blue', 'Linear'='purple'))
p_sep_by_corpus

# 3. Canonical proportion by age, colored by child sex
p_sex <- ggplot(df, aes(x = age_mo_round, y = cp, color = child_gender)) + geom_point() + 
  xlab("Age (months)") + ylab("Canonical proportion") + 
  theme(legend.position="right") +
  guides(colour = guide_legend(nrow = 4)) + 
  theme(legend.title=element_blank()) + 
  geom_point(size=3)
p_sex

```

